[build]
builder = "NIXPACKS"

[nixpacks]
install_cmd = "cd backend && npm install"

# Явно указываем, что используем volume
[deploy]
startCommand = "cd backend && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Настройка томов
[[volumes]]
name = "data"
mountPath = "/data" 